# Generated by Django 3.1.4 on 2020-12-24 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import main.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=200, unique=True)),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("category_slug", models.CharField(max_length=200, unique=True)),
            ],
            options={"verbose_name_plural": "Categories",},
            bases=(models.Model, main.mixins.BaseModelMixin, main.mixins.JSONifyMixin),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=200, unique=True)),
                ("summary", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "date_published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                ("item_slug", models.CharField(max_length=200, unique=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "category_name",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Items",},
            bases=(models.Model, main.mixins.BaseModelMixin, main.mixins.JSONifyMixin),
        ),
    ]
