# Generated by Django 3.2.11 on 2022-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_thumbnail",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
